### ISSUE TITLE
Did you use unrolling in the experiments?

### ISSUE THREAD

**Issue by moskomule** [xiangning-chen/SmoothDARTS#3]
Hi, thank you for sharing your code. I have a question about the unrolling.

https://github.com/xiangning-chen/SmoothDARTS/blob/83710f1249be2d8e2f85ca802b0aa3bf12d875dd/sota/cnn/train_search.py#L52

This flag is false by default, and the execution command presented in `README.md` is, for example, `SDARTS-RS: cd sota/cnn && python train_search.py --search_space=s1 --perturb_alpha=random`. Did you use `unrolled` in the main experiments?

**Comment by xiangning-chen** [comment]
Hi, thanks for your question. I used unrolled=False to search for architectures in all my experiments.
