### ISSUE TITLE
Parameter-free ops still dominate the generated architecture?

### ISSUE THREAD

**Issue by SlimFun** [xiangning-chen/SmoothDARTS#7]
Hi. 

Thanks for your release code. Great job! 
But when I ran the experiments on s1(Cifar10), it seemed to get completely different results from the paper: No matter I use random or pgd_linf method, almost all operations I got when the search finished still are skip_conn. Are there some special tricks or hyperparameter setting that are not mentioned during the experiment?

Look forward to your reply.Thanks.

**Comment by xiangning-chen** [comment]
Hi,

Thanks for your attention. You may increase the perturbation strength: --epsilon_alpha.
