### ISSUE TITLE
ImageNet training details

### ISSUE THREAD

**Issue by Minione** [xiangning-chen/SmoothDARTS#8]
Dear authors,

Thanks for providing the code of SDARTS.

I noticed that in sota/cnn/train_imagenet.py the batch_size is set to 1024. Does that mean the ImageNet results of SDARTS in the paper were obtained with 8-GPU training, i.e., the same setup used by PC-DARTS / P-DARTS?

Thanks!

**Comment by Minione** [comment]
BTW, if you still have the information, could you kindly provide the cell designs found by SDARTS on CIFAR-10 from the original DARTS space? I only found cells found from S1-4 space in sota/cnn/genotypes.py but not those found from the DARTS space. Thanks!

**Comment by xiangning-chen** [comment]
> Dear authors,
> 
> Thanks for providing the code of SDARTS.
> 
> I noticed that in sota/cnn/train_imagenet.py the batch_size is set to 1024. Does that mean the ImageNet results of SDARTS in the paper were obtained with 8-GPU training, i.e., the same setup used by PC-DARTS / P-DARTS?
> 
> Thanks!

Thanks for your attention. Yes, we use 8-GPU to train our models on ImageNet.

**Comment by xiangning-chen** [comment]
> BTW, if you still have the information, could you kindly provide the cell designs found by SDARTS on CIFAR-10 from the original DARTS space? I only found cells found from S1-4 space in sota/cnn/genotypes.py but not those found from the DARTS space. Thanks!

The DARTS space is S5, so you can find the searched cells here: https://github.com/xiangning-chen/SmoothDARTS/blob/master/sota/cnn/genotypes.py#L26

**Comment by Minione** [comment]
Thanks for the prompt reply! That's super helpful!
